// actionTypes.js
// export const FETCH_USER_DETAILS_REQUEST = "FETCH_USER_DETAILS_REQUEST";
// export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
// export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

// export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
// export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
// export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";
// export const ActionTypes = {
//   SET_PRODUCTS: "SET_PRODUCTS",
//   SELECTED_PRODUCT: "SELECTED_PRODUCT",
//   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
// };
export const ActionTypes = {
  FETCH_USER_REQUEST: "FETCH_USER_DETAILS_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_DETAILS_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_DETAILS_FAILURE",

  // UPDATE_USER_REQUEST: "UPDATE_USER_DETAILS_REQUEST",
  // UPDATE_USER_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
  // UPDATE_USER_FAILURE: "UPDATE_USER_DETAILS_FAILURE",

  // UPDATE_PROFILE_PIC: "UPDATE_PROFILE_PIC",
  // UPDATE_PROFILE_PIC_SUCCESS: "UPDATE_PROFILE_PIC_SUCCESS",
  // UPDATE_PROFILE_PIC_FAILURE: "UPDATE_PROFILE_PIC_FAILURE",

  // DELETE_PROFILE_PIC: "UPDATE_PROFILE_PIC",
  // DELETE_PROFILE_PIC_SUCCESS: "UPDATE_PROFILE_PIC_SUCCESS",
  // DELETE_PROFILE_PIC_FAILURE: "UPDATE_PROFILE_PIC_FAILURE",
};
